### PR TITLE
Update ecopoint_ev_charger.yaml

### PR DESCRIPTION
**Pull request by mat1990dj**
Add support for Nine charger. verified DP IDs with tuya api explorer to match as well as the modes

### CODE REVIEW

**Comment by make-all** [comment]
The matching is by dps.  You can test it against the log message of actual dps received using the scripts in util.

`python util/best_match.py 'JSON DPS LOG'` will show the best matches for the device as it was seen in that log message.
`python util/match_against.py ecopoint_ev_charger.yaml 'JSON DPS LOG'` will show where the log is not matching the config.

**Comment by mat1990dj** [comment]
> The matching is by dps. You can test it against the log message of actual dps received using the scripts in util.
> 
> `python util/best_match.py 'JSON DPS LOG'` will show the best matches for the device as it was seen in that log message. `python util/match_against.py ecopoint_ev_charger.yaml 'JSON DPS LOG'` will show where the log is not matching the config.

Do you have a guide on how to run those utils? I tried setting up the project dev env on my computer but it's complaining about No module named 'homeassistant'

**Comment by mat1990dj** [comment]
Ok, I figured it out, I'm now matching correctly at 100% but I've got one issue, if you see the mapping on DPs 6-9 it's a base64 (CXQAUtAT2g== for instance, but this decodes to 09740052d013da, voltage is the first four 0974 but this is in HEX and not directly decimal, 0974 decodes to 2420 which is 242,0V. How can I indicate a mapping to do base64 AND HEX from the result?

**Comment by feeling001** [comment]
Can I suggest an improvement ? 
The scale is incorrect on the "Charging Curent" entity.  scale 10 should be scale 1 (actually 16amp show as 1.6amp)
The range is also incorrect. from 6-80 to 6-32

Here is a correction.

 ```
 - entity: number
    name: Charging current
    category: config
    class: current
    icon: "mdi:ev-plug-type2"
    dps:
      - id: 4  # charge_cur_set
        type: integer
        name: value
        unit: A
        optional: true
        range:
          min: 6
          max: 32
        mapping:
          - scale: 1

```

Best regards.

**Pull request closed without merging**
