### PR TITLE
extended support for mh1823d

### PR DESCRIPTION
**Pull request by apoplavs**
* data from internal sensor
* Set temperature entity

### CODE REVIEW

**Comment by make-all** [comment]
These changes just duplicate information that is already accessible through the climate entity.

**Comment by apoplavs** [comment]
> These changes just duplicate information that is already accessible through the climate entity.

@make-all Without these changes user can build automation using only external sensor.

**Comment by apoplavs** [comment]
file:///home/andrii/screen.png

**Comment by make-all** [comment]
You are mistaken.  I can't see enough of the screen behind there to tell what you are looking at and why you have gotten this impression, but it is entirely possible to use the Current Temperature attribute of climate entities in a Numeric State trigger, and to call the Set Temperature service on a climate entity as an action.

**Comment by apoplavs** [comment]
ok, thanks lot

**Pull request closed without merging**
