### PR TITLE
Added support for V330L-DU4L-VS pet feeder

### PR DESCRIPTION
**Pull request by e2equiel**
Captura de Pantalla 2024-07-12 a la(s) 15 19 07

### CODE REVIEW

**Comment by e2equiel** [comment]
Can't make work DP 115 (snapshot):
```json
{
  "result": {
    "properties": [
      {
        "code": "movement_detect_pic",
        "custom_name": "",
        "dp_id": 115,
        "time": 1720804936027,
        "type": "raw",
        "value": "eyJ2IjoiMy4wIiwiYnVja2V0IjoidHktdXMtc3RvcmFnZTMwLXBpYyIsImZpbGVzIjpbWyIvODc4MTViLTgyMTY5MjQwLWd6ams5ZGFiN2ZlNmEwMDY3MDEyL2RldGVjdC8xNzIwODA0OTI5LmpwZWciLCIzNWUzY2NmMWYwMjAzZmM1Il1dfQ=="
      }
    ]
  },
  "success": true,
  "t": 1720809674649,
  "tid": "514e70fd407e11ef8e43562584fc0bdb"
```

When undecode the base64 value, it return another json and I don't know how to use it:
```json
{"v":"3.0","bucket":"ty-us-storage30-pic","files":[["/87815b-82169240-gzjk9dab7fe6a0067012/detect/1720804929.jpeg","35e3ccf1f0203fc5"]]}
```

I will appreciate any help

**Comment by e2equiel** [comment]
I'm not sure if this would help, but I just figured how to access via telnet to the pet feeder:
```bash
telnet xxx.xxx.xxx.xxx
ipc login: root
Password: AK2040jk
```

**Comment by make-all** [comment]
Arbitrary decoding of double encoded base64 image within json within base64 is not feasible, so it may be better to rename that attribute so the base64 decoded value can still be read so the image can be extracted by another more specialised integration or complex template, but it does not give any errors trying to use it as the snapshot directly.

**Comment by make-all** [comment]
Your latest change seems to have lost the record switch.  I was actually meaning to make the image json an attribute of the camera entity named something else (snapshot_data would have worked), and leave the record function in there, but I guess having such a limited camera entity maybe does not make much sense.  But a sensor entity for the snapshot data is not really necessary, as I don't think you would want it to show in the UI by default, so maybe keeping the record as a switch and putting the snapshot attribute on there would work.

**Comment by e2equiel** [comment]
Hi @make-all, do you mean something like this?
```yaml
  - entity: switch
    name: Record
    icon: "mdi:record-rec"
    category: config
    dps:
      - id: 113
        type: boolean
        optional: true
        name: record
        mapping:
          - dps_val: null
            value: false
      - id: 115
        type: base64
        name: snapshot_data
        optional: true
```

**Comment by make-all** [comment]
yes

**Comment by pergolafabio** [comment]
> I'm not sure if this would help, but I just figured how to access via telnet to the pet feeder:
> 
> ```shell
> telnet xxx.xxx.xxx.xxx
> ipc login: root
> Password: AK2040jk
> ```

Wow, how did you find that telnet password? it seems to work also for me on my v330 model with the other product id
are you on discord? can i contact you ?

**Comment by e2equiel** [comment]
> > I'm not sure if this would help, but I just figured how to access via telnet to the pet feeder:
> > ```shell
> > telnet xxx.xxx.xxx.xxx
> > ipc login: root
> > Password: AK2040jk
> > ```
> 
> Wow, how did you find that telnet password? it seems to work also for me on my v330 model with the other product id are you on discord? can i contact you ?

I didn't find by myself, I just find this article googling around: [https://www.linkedin.com/pulse/snhack-attack-how-hackers-could-turn-your-smart-pet-feeder-bongiorni-fxtsf](https://www.linkedin.com/pulse/snhack-attack-how-hackers-could-turn-your-smart-pet-feeder-bongiorni-fxtsf)... just lucky I guess

**Comment by e2equiel** [comment]
> ah ok :-) was looking for a way to enable the rtsp port, seems 554 is not open on my petfeeder
> 
> i have this model
> 
> image

I looked to enable rtsp port too, but I think it's impossible, at least in my model... Good luck my friendo!

**Comment by pergolafabio** [comment]
thx, gonna try readding the device in tuya local, seems you added a lot of new entities :-)

**Comment by pergolafabio** [comment]
hi @e2equiel , i tried readding it with your V330L-DU4L-VS Petfeeder model

if i add it using 3.2 , i dont get the prompt to add it like, that only with my model?

image

```
name: Pet feeder
products:
  - id: ibnk6keua0zzc2gr
    name: V330 Petfeeder
  - id: cjrm04np59ut4pwb
    name: V330L-DU4L-VS Petfeeder
```

any idea?

**Comment by pergolafabio** [comment]
i only see these entities below, how does yours look like?

image

**Comment by e2equiel** [comment]
@pergolafabio yes, mine looks exactly like yours

**Comment by pergolafabio** [comment]
But i see you added a lot of more DPI entities in the yaml file, where are all those entities?

**Comment by e2equiel** [comment]
Yes, at first I tried adding those extra DPIs, but, none of them worked. So I just go with the same DPI as you

**Comment by pergolafabio** [comment]
Btw, you can use the tuya cloud integration for grabbing the camera feed

**Comment by e2equiel** [comment]
@pergolafabio thanks for the info! I don't know how to give you my discord without making it public 😞

**Comment by pergolafabio** [comment]
try finding me with username "fabiopergola" or fabiopergola#9662

**Pull request merged**
