### PR TITLE
add Feyree 3 phase 22kw ev charger yaml

### PR DESCRIPTION
**Pull request by daseth**
Added yaml file for the Feyree 3 phase 22kw ev charger. https://s.click.aliexpress.com/e/_ExRRpyL
The charger was initially recognized as the goodcell ev charger (goodcell_ev_charger.yaml), and not as the existing Feyree 1phase wallbox.

### CODE REVIEW

**Comment by make-all** [comment]
This doesn't appear to be sufficiently different than the Goodcell device to justify a new config.
Was there an issue that prevented you from using that?

**Comment by daseth** [comment]
> This doesn't appear to be sufficiently different than the Goodcell device to justify a new config. Was there an issue that prevented you from using that?

Yes. First, the minimum current that could be set with Goodcell is 6A, but with the Feyree Charger it is 8A. 

Also the charge session duration was not present in the Goodcell configuration. I have added it to my configuration.

I have also used the existing Feyree yaml for the 1-phase model to match the fault codes from dpid 10 (fault_code) to explicit faults. This was something not present in the Goodcell yaml.

I consider the PR valuable since it might help users for the specific model get all the sensors, match the minimum current (8A) and get explicit understanding on the fault code.

**Comment by philippedeswert** [comment]
> Yes. First, the minimum current that could be set with Goodcell is 6A, but with the Feyree Charger it is 8A.

As I originally did the Goodcell. I added 6A on purpose, as most cars will charge at 6A. The Tuya app unfortunately only goes down to 8A. This makes it possible to make better use of solar energy. You can most likely do the same with the Feyree.

**Comment by daseth** [comment]
> > Yes. First, the minimum current that could be set with Goodcell is 6A, but with the Feyree Charger it is 8A.
> 
> As I originally did the Goodcell. I added 6A on purpose, as most cars will charge at 6A. The Tuya app unfortunately only goes down to 8A. This makes it possible to make better use of solar energy. You can most likely do the same with the Feyree.

I can confirm that you can set it to 6A from Home assistant, although both the Tuya app and the charger's display do not allow it. For this device, I considered it prudent to keep with the manufacturer's limitation, and not allow it to 6A. 
Does the Goodcell also prevent you from setting it to 6A on the Tuya app and on the wall box's menu?

**Comment by philippedeswert** [comment]
> > As I originally did the Goodcell. I added 6A on purpose, as most cars will charge at 6A. The Tuya app unfortunately only goes down to 8A. This makes it possible to make better use of solar energy. You can most likely do the same with the Feyree.
> 
> I can confirm that you can set it to 6A from Home assistant, although both the Tuya app and the charger's display do not allow it. For this device, I considered it prudent to keep with the manufacturer's limitation, and not allow it to 6A. Does the Goodcell also prevent you from setting it to 6A on the Tuya app and on the wall box's menu?

As stated yes the app limits to 8A, and also the UI. I understand the concern, but I found it useful to have 6A and thought it would be nice to be able to make the product more useful than in standard form.  As this is really nice if you charge at home from solar and you don't want to pull from the grid. Since it expands the time frame where you can charge.  I just wanted to give you/others the background why the Goodcell implementation ignored the 8A lower end setting (low risk as higher currents is where the danger lies). Anyway good to see other charger models working!

**Comment by daseth** [comment]
> > > As I originally did the Goodcell. I added 6A on purpose, as most cars will charge at 6A. The Tuya app unfortunately only goes down to 8A. This makes it possible to make better use of solar energy. You can most likely do the same with the Feyree.
> > 
> > 
> > I can confirm that you can set it to 6A from Home assistant, although both the Tuya app and the charger's display do not allow it. For this device, I considered it prudent to keep with the manufacturer's limitation, and not allow it to 6A. Does the Goodcell also prevent you from setting it to 6A on the Tuya app and on the wall box's menu?
> 
> As stated yes the app limits to 8A, and also the UI. I understand the concern, but I found it useful to have 6A and thought it would be nice to be able to make the product more useful than in standard form. As this is really nice if you charge at home from solar and you don't want to pull from the grid. Since it expands the time frame where you can charge. I just wanted to give you/others the background why the Goodcell implementation ignored the 8A lower end setting (low risk as higher currents is where the danger lies). Anyway good to see other charger models working!

This is what happens to me when i allow values lower than 8A: i can set values lower than 8A (so 7A or 6A are possible) and the device itself will accept them. But Home assistant will revert the resulting sensor to 8A. On the device itself there is no change, it will keep the lower value I set it to.

I would not mind this much, but i have a 2 buttons in HA that increment/decrement this number. And they will always decrement from what HA shows (not from what is actually on the device). Is your behavior the same? Did you find a fix for this?

**Comment by rthsw** [comment]
Help needed on build a YAML for a Feyree 1 Phase 7Kw Charger... and where to put?

In Short: 
**How do i add a device to LocalTuya by an YAML File?** 

Hi, i have a Feyree 1 Phase 7Kw Charger, and i have a running "LocalTuya integration" under HACS.
My Charger was discovered by the HACS "Xtend Tuya", so i could download the Diagnostic Data, so i found the existing DPS_Strings.
Xtend Tuya only shows me the Sensors **Balance Energy**, **Charge Energy**, **Work State** and the Configuration **Clear energy**, **Schalter** (=Switch) and "Work mode" with the options **Real time charging, Charge to percentage, Charge Energy, Scheduled charge**. Nothing else. Maybe "Schalter" could be the one which starts the charging, but there is no reaction of the physical device if i press the "Schalter". Even if i switch the Work Mode to "Charge to percentage", i can not set the percentage. There are no hidden Entitys. 

With this Information, i found this YAML very close to my Feyree:
https://github.com/vm03/esphome-feyree-ev-charger/blob/master/feyreeev.yaml (But this is a ESP32 modification!)
or
https://github.com/make-all/tuya-local/pull/2106/commits/cf6b00d438538e8a87474864381cc413a25f91e7 (This looks very close to my DPS)
Close enough so i can edit with my "Try and Error" modification.

How can i integrate this or better my modified YAML to the LocalTuya?

When i add this device to my LocalTuya, it is auto discovered, but i need to add every single DPS by Hand by an more than uncomfortable Way, and in a case of mistake i need to delete the whole device and start again from zero. E.g. i added the DPS 123 (value:False) as an binary sensor, because of the "false": But 123 is in fact not a sensor, it is the Switch "Start Charging". I did not find a way to change the type of an entity in LocalTuya after i insert it. So, i think it is easier to modify it direct in a YAML File...

But how do i add a device to LocalTuya by an YAML File? 
I thought i only need to put the new File with "Studio Code Server" at the newly created Directory /config/custom_components/localtuya/devices/feyree_1Phase_ev_charger_rfid.yaml
but nothing happend in LocalTuya. Or is there a special way i need to follow to select this YAML for my new device?
If i try to delete the old, wrong by hand configured Device, i get the error Error on deleting the Device: "Unknown error" (German: 

Fehler beim Löschen des Geräts 
Unknown Error 
[OK]
After a Homeassistant Reboot i could first deactivate the device and then delete.

For my first try i use the "close enough" file, changed the first lines to 
name: EV charger
products:
  - id: bf51e4686a8a0586b9stda
    name: Feyree 32A 85-264V 1 phase EV charger
and save this YAML File here:
/config/custom_components/localtuya/devices/feyree_1Phase_ev_charger_rfid.yaml
But... 
After i delete, i could add the autodiscovered Device. LocalTuya identifies the Host Adress, the  Device ID, the local Key, the protocol Version.
Next step i can add "Entity type selection, Please pic the type of entity you want to add. Platform* switch (pre-selectet).
But... I thought LocalTuya will somehow identify the ready to use YAML Defintion! No, nothing i need to configure every single Entity by hand (and i don't know the exact platform etc. i need to choose for every entity, and a single mistake stops the whole process).




**My Debug/Diagnostic file where i found the existing DPS:**
(i removed the intro and only leave the interesting part... as far as i understand)

  "setup_times": {},
  "data": {
    "device_config": {
      "friendly_name": "feyree",
      "host": "192.168.99.194",
      "device_id": "bf51e4686a8a0586b9stda",
      "local_key": "@+6_iBZ~af]~]#6A",
      "protocol_version": "3.4",
      "enable_debug": true,
      "model": "feyree",
      "dps_strings": [
        "10 (value: 0)",
        "101 (value: connect)",
        "102 (value: 2266)",
        "103 (value: 0)",
        "104 (value: 0)",
        "105 (value: 0)",
        "106 (value: 0)",
        "107 (value: 0)",
        "109 (value: 0)",
        "110 (value: 334)",
        "112 (value: 0)",
        "113 (value: Max32A)",
        "115 (value: 20)",
        "118 (value: 0)",
        "119 (value: 0)",
        "120 (value: 00:00:00)",
        "121 (value: T:00H)",
        "122 (value: D:00H)",
        "123 (value: False)",
        "124 (value: WaitOperation)",
        "125 (value: 20)"
      ],
      "entities": [
        {
          "id": 125,
          "friendly_name": "ChargingAmpere",
          "restore_on_reconnect": false,
          "is_passive_entity": false,
          "platform": "switch"
        }
      ],
      "product_key": "basqjlsmzcq8ipva"
    },
    "device_cloud_info": {
      "active_time": 1753507349,
      "biz_type": 18,
      "category": "qccdz",
      "create_time": 1753507349,
      "icon": "smart/icon/bay16226250696545rLI/169985857684fb0805bf7.png",
      "id": "bf51e4686a8a0586b9stda",
      "ip": "49.145.227.77",
      "lat": "0",
      "local_key": "@+6_iBZ~af]~]#6A",
      "lon": "0",
      "model": "",
      "name": "feyree",
      "online": true,
      "owner_id": "27589385",
      "product_id": "basqjlsmzcq8ipva",
      "product_name": "feyree",
      "status": [
        {
          "code": "work_state",
          "value": "charger_free"
        },
        {
          "code": "work_mode",
          "value": "charge_now"
        },
        {
          "code": "balance_energy",
          "value": 0
        },
        {
          "code": "clear_energy",
          "value": true
        },
        {
          "code": "switch",
          "value": true
        },
        {
          "code": "charge_energy_once",
          "value": 1
        }
      ],
      "sub": false,
      "time_zone": "+08:00",
      "uid": "eu1615844470867wpZMw",
      "update_time": 1753570768,
      "uuid": "141baff6fea79e69"
    }
  }
}

**The Yaml i found "Very Close" (https://github.com/make-all/tuya-local/pull/2106/commits/cf6b00d438538e8a87474864381cc413a25f91e7)**
There is e.g. a DPS 3, i don't get on my Diagnostic Data, and there is missing the DPS 10.

name: EV charger
products:
  - id: j6bzjwhiv2cljjcy
    name: Feyree 32A 85-264V 3 phase EV charger
primary_entity:
  entity: sensor
  class: enum
  name: EV Wallbox Status
  icon: "mdi:ev-station"
  dps:
    - id: 101
      type: string
      name: sensor
      mapping:
        - dps_val: no_connet
          value: Disconnected
        - dps_val: connect
          value: Connected
        - dps_val: charing
          value: Charging
        - dps_val: wait_rfid
          value: Waiting for authorization
        - dps_val: finish
          value: Charged
        - dps_val: wait_charing
          value: Delaying charge
        - dps_val: error
          value: Error
    - id: 3
      type: string
      optional: true
      name: charger_status
      mapping:
        - dps_val: charger_free
          value: Standby
        - dps_val: charger_insert
          value: Cable connected
        - dps_val: charger_free_fault
          value: Charger fault
        - dps_val: charger_wait
          value: Charger ready
        - dps_val: charger_charging
          value: Charging
        - dps_val: charger_pause
          value: Charging paused
        - dps_val: charger_end
          value: Charging ended
        - dps_val: charger_fault
          value: Charger fault
    - id: 10
      type: bitfield
      name: fault_code
    - id: 11
      type: string
      optional: true
      name: alarm_set_1
    - id: 12
      type: string
      optional: true
      name: alarm_set_2
    - id: 14
      type: string
      optional: true
      name: mode
      mapping:
        - dps_val: charge_now
        - dps_val: charge_pct
        - dps_val: charge_energy
        - dps_val: charge_schedule
    - id: 15
      type: integer
      optional: true
      name: balance_energy
      unit: kWh
    - id: 18
      type: boolean
      optional: true
      name: switch
    - id: 23
      type: string
      optional: true
      name: system_version
    - id: 25
      type: integer
      optional: true
      name: charge_energy_once
      unit: kWh
    - id: 27
      type: string
      optional: true
      name: online_state
secondary_entities:
  - entity: button
    name: EV Wallbox Clear energy
    class: restart
    category: config
    dps:
      - id: 16
        type: boolean
        name: button
        optional: true
  - entity: number
    name: EV Wallbox Set charging current
    category: config
    icon: "mdi:ev-plug-type2"
    dps:
      - id: 115
        type: integer
        name: value
        unit: A
        range:
          min: 8
          max: 32
        mapping:
          - constraint: max_current
            conditions:
              - dps_val: Max16A
                value_redirect: value_alt
                range:
                  min: 8
                  max: 16
      - id: 114
        type: integer
        name: value_alt
        unit: A
        range:
          min: 8
          max: 16
      - id: 113
        type: string
        name: max_current
        mapping:
          - dps_val: Max16A
            value: Max16A
          - dps_val: Max32A
            value: Max32A
  - entity: number
    name: EV Wallbox Set Delay Time Hours
    category: config
    icon: "mdi:car-clock"
    dps:
      - id: 118
        type: integer
        name: value
        unit: h
        range:
          min: 0
          max: 15
  - entity: sensor
    name: EV Wallbox Charging Session Delivered Energy
    class: energy
    dps:
      - id: 112
        type: integer
        name: sensor
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 1 Voltage
    class: voltage
    category: diagnostic
    dps:
      - id: 102
        type: integer
        name: sensor
        unit: V
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 2 Voltage
    class: voltage
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: V
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 3 Voltage
    class: voltage
    category: diagnostic
    dps:
      - id: 104
        type: integer
        name: sensor
        unit: V
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 1 Current
    class: current
    category: diagnostic
    dps:
      - id: 105
        type: integer
        name: sensor
        unit: A
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 2 Current
    class: current
    category: diagnostic
    dps:
      - id: 106
        type: integer
        name: sensor
        unit: A
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 3 Current
    class: current
    category: diagnostic
    dps:
      - id: 107
        type: integer
        name: sensor
        unit: A
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Charging Power
    class: power
    dps:
      - id: 109
        type: integer
        name: sensor
        unit: kW
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Temperature
    class: temperature
    category: diagnostic
    dps:
      - id: 110
        type: integer
        name: sensor
        unit: C
        class: measurement
        mapping:
          - scale: 10
  - entity: number
    name: EV Wallbox Set Charging Duration
    category: config
    icon: "mdi:car-clock"
    dps:
      - id: 119
        type: integer
        name: value
        unit: h
        range:
          min: 0
          max: 15
  - entity: select
    name: EV Wallbox Set StartStop
    icon: "mdi:ev-plug-type2"
    category: config
    dps:
      - id: 124
        type: string
        name: option
        mapping:
          - dps_val: "OpenCharging"
            value: Start charging
          - dps_val: "CloseCharging"
            value: Stop charging
          - dps_val: "WaitOperation"
            value: Waiting for command
  - entity: sensor
    name: EV Wallbox Charging session duration
    icon: "mdi:car-clock"
    dps:
      - id: 120
        type: string
        name: sensor

The File from which seems to be very close to the YAML i need:
name: EV charger
products:
  - id: j6bzjwhiv2cljjcy
    name: Feyree 32A 85-264V 3 phase EV charger
primary_entity:
  entity: sensor
  class: enum
  name: EV Wallbox Status
  icon: "mdi:ev-station"
  dps:
    - id: 101
      type: string
      name: sensor
      mapping:
        - dps_val: no_connet
          value: Disconnected
        - dps_val: connect
          value: Connected
        - dps_val: charing
          value: Charging
        - dps_val: wait_rfid
          value: Waiting for authorization
        - dps_val: finish
          value: Charged
        - dps_val: wait_charing
          value: Delaying charge
        - dps_val: error
          value: Error
    - id: 3
      type: string
      optional: true
      name: charger_status
      mapping:
        - dps_val: charger_free
          value: Standby
        - dps_val: charger_insert
          value: Cable connected
        - dps_val: charger_free_fault
          value: Charger fault
        - dps_val: charger_wait
          value: Charger ready
        - dps_val: charger_charging
          value: Charging
        - dps_val: charger_pause
          value: Charging paused
        - dps_val: charger_end
          value: Charging ended
        - dps_val: charger_fault
          value: Charger fault
    - id: 10
      type: bitfield
      name: fault_code
    - id: 11
      type: string
      optional: true
      name: alarm_set_1
    - id: 12
      type: string
      optional: true
      name: alarm_set_2
    - id: 14
      type: string
      optional: true
      name: mode
      mapping:
        - dps_val: charge_now
        - dps_val: charge_pct
        - dps_val: charge_energy
        - dps_val: charge_schedule
    - id: 15
      type: integer
      optional: true
      name: balance_energy
      unit: kWh
    - id: 18
      type: boolean
      optional: true
      name: switch
    - id: 23
      type: string
      optional: true
      name: system_version
    - id: 25
      type: integer
      optional: true
      name: charge_energy_once
      unit: kWh
    - id: 27
      type: string
      optional: true
      name: online_state
secondary_entities:
  - entity: button
    name: EV Wallbox Clear energy
    class: restart
    category: config
    dps:
      - id: 16
        type: boolean
        name: button
        optional: true
  - entity: number
    name: EV Wallbox Set charging current
    category: config
    icon: "mdi:ev-plug-type2"
    dps:
      - id: 115
        type: integer
        name: value
        unit: A
        range:
          min: 8
          max: 32
        mapping:
          - constraint: max_current
            conditions:
              - dps_val: Max16A
                value_redirect: value_alt
                range:
                  min: 8
                  max: 16
      - id: 114
        type: integer
        name: value_alt
        unit: A
        range:
          min: 8
          max: 16
      - id: 113
        type: string
        name: max_current
        mapping:
          - dps_val: Max16A
            value: Max16A
          - dps_val: Max32A
            value: Max32A
  - entity: number
    name: EV Wallbox Set Delay Time Hours
    category: config
    icon: "mdi:car-clock"
    dps:
      - id: 118
        type: integer
        name: value
        unit: h
        range:
          min: 0
          max: 15
  - entity: sensor
    name: EV Wallbox Charging Session Delivered Energy
    class: energy
    dps:
      - id: 112
        type: integer
        name: sensor
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 1 Voltage
    class: voltage
    category: diagnostic
    dps:
      - id: 102
        type: integer
        name: sensor
        unit: V
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 2 Voltage
    class: voltage
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: V
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 3 Voltage
    class: voltage
    category: diagnostic
    dps:
      - id: 104
        type: integer
        name: sensor
        unit: V
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 1 Current
    class: current
    category: diagnostic
    dps:
      - id: 105
        type: integer
        name: sensor
        unit: A
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 2 Current
    class: current
    category: diagnostic
    dps:
      - id: 106
        type: integer
        name: sensor
        unit: A
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Phase 3 Current
    class: current
    category: diagnostic
    dps:
      - id: 107
        type: integer
        name: sensor
        unit: A
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Charging Power
    class: power
    dps:
      - id: 109
        type: integer
        name: sensor
        unit: kW
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: EV Wallbox Temperature
    class: temperature
    category: diagnostic
    dps:
      - id: 110
        type: integer
        name: sensor
        unit: C
        class: measurement
        mapping:
          - scale: 10
  - entity: number
    name: EV Wallbox Set Charging Duration
    category: config
    icon: "mdi:car-clock"
    dps:
      - id: 119
        type: integer
        name: value
        unit: h
        range:
          min: 0
          max: 15
  - entity: select
    name: EV Wallbox Set StartStop
    icon: "mdi:ev-plug-type2"
    category: config
    dps:
      - id: 124
        type: string
        name: option
        mapping:
          - dps_val: "OpenCharging"
            value: Start charging
          - dps_val: "CloseCharging"
            value: Stop charging
          - dps_val: "WaitOperation"
            value: Waiting for command
  - entity: sensor
    name: EV Wallbox Charging session duration
    icon: "mdi:car-clock"
    dps:
      - id: 120
        type: string
        name: sensor

**Pull request merged**
