### PR TITLE
Fix cover actions - Add zemismart roller

### PR DESCRIPTION
**Pull request by xZetsubou**
Hello, after many tests to fix actions and #655 didn't really fully fix the issues.
By far this the best way I found to detect cover actions, this PR fixing and improving that.

# Summery:
- Added device Zemismart Ignoring the action DP.
- Fix open/close stuck states.
- Detect whether the state is opening/closing even with set position.

### CODE REVIEW

**Comment by make-all** [comment]
It seems you have broken three other devices with this change

**Comment by xZetsubou** [comment]
These test devices doesn't handle None or false values which is weird because it's not necessary ```is_opening``` or ```is_closing``` need to return True value all the time if it's stopped both of them will return false or None, At least it should be like that.
**I might be wrong** either way, I tweaked the codes to these handle devices.

**Comment by make-all** [comment]
I have cleaned up the logic of is_opening, is_closing and is_closed, and renamed the "action" dp on zemismart roller to reflect its unreliability.

I hope this can address the issues you are facing.

I did this rather than accept the PR as it is, because I do not think that keeping internal state based on previous commands will be a workable solution, as the device can also be operated from its own control panel or remote control, and the cloud app, so the likelihood of internal state getting out of sync is high.

**Comment by xZetsubou** [comment]
I agree with you that's not the best solution, but this's the only solution as far as I know to detect the actual state, most of Tuya covers won't return the current state if it's not all of them, your changes [4aad42f](https://github.com/make-all/tuya-local/commit/4aad42fe0814ccf02c8ffe5b389fcc46da4e2b00) returning [unknown value](https://user-images.githubusercontent.com/46300268/236665695-8b3c5f7f-f09e-40ff-9619-ea4ed6293e1d.png) and when I use set position the state will stuck again whether [opening or closing](https://user-images.githubusercontent.com/46300268/236665723-0c7f49a4-766c-4e58-9217-a05110ff8aae.png) so set position and open/close actions won't works as it should be. 
we can sync states with current pos value in case device begin controlled by out of HA.
I won't force my solution I can rewrite cover.py locally it's fine, but I just wanted to fix this issue since cover state might be important for some people making automations.
Thanks for trying to fix this if you want me to try other fixes I wouldn't mind to test ^^

**Comment by make-all** [comment]
Maybe it will help if you can explain what the exact state of all the dp are in various situations (both working and not working).

Part of the difficulty for me is that I do not have this device to see how it is acting.  Maybe we can use the action, just not in the direct way we are using it now, for example.  I see other configs use the current_position to allow it to also represent opened and closed states, so I made that change.  But depending on how dp 11 is working, it may be a better candidate for detecting opened/closed states.

Also, it may be worth adding `persist: false` to the command dp, maybe it will then get cleared instead of outdated commands staying and interfering with the open/close/opening/closing detection.

**Comment by xZetsubou** [comment]
Detecting closed or opened isn't big deal, but the issue is with `opening` and `closing`,
 `is_opening` shouldn't return true unless the motor moving up `if pos < 95 and cmd is open` that means the state will always be `opening` as default state which will lead HA to disable `open` button.  same goes for `closing` will lead HA to disable `close` button. HA have `is_opening and is_closing` assuming that there's an action DP return whether `opening or closing or stopped` probably tuya covers doesn't have this?

- Open/Close won't update `DP 1` value to new states on the cloud so you can't relay on last cmd to detect action
  `when device reconnected cmd is always is open thats why it's stuck in opening at start this the main issue.`
  `this also why I set the default value of _current_state is stop`
- `DP 2` is the actual current pos and would be updating after open, close and set position.
- `DP 11` Won't change at all its probably broken as well.
- Open/Close won't update _currentpos_dp `DP 3` this only updated using set position.
- Using set position `DP 3` won't always update current pos `DP 2` unless the cover moved by 10 steps at least for my cover, 
  so it will only move the if inserted position `DP 2` > 5 OR  `DP 2` < -5  `This is how I detect action by set position`

So to fully relay on Tuya cloud states to detect current action perfectly all the time is I don't know if there's good way, using open and close won't change any DP till the cover stops then it will only update current pos `DP 2` to the new position.
Also this issue's in official Tuya integration the opening action won't be detected.

This Comment after I tested https://github.com/make-all/tuya-local/commit/546c0b013054abfb484a999946f637e5e09e54b1 https://github.com/make-all/tuya-local/commit/ba6edb54ff3b39d171fcb5a0d5036c29e82b4b9d

**Pull request closed without merging**
