### PR TITLE
Add the ElectriQ CD12PRO-LE dehumidifier

### PR DESCRIPTION
**Pull request by cooperaj**
Found that my new dehumidifier wasn't in the repo so added it :) 

Didn't know if I was supposed to add the contribution line but can remove if it shouldn't be a part of this PR.

### CODE REVIEW

**Comment by cooperaj** [comment]
I don't supposed I could have a label added for "that yearly github event" please ;) I'm missing one last thing.

**Comment by cooperaj** [comment]
Mmm. Not sure how to fix this sonarcloud issue? Looks to be some sort of permissions check on it.

**Comment by make-all** [comment]
Don't worry about the sonarcloud issue, it is due to test coverage in the newly added water_heater implementation that was basically copied from climate so has a lot of code that isn't actually needed for the one device that uses it.

**Comment by make-all** [comment]
Merged

**Pull request closed without merging**
