### PR TITLE
Update rotenso_ronix_heatpump.yaml

### PR DESCRIPTION
**Pull request by piotrek2555**
Change range temperature from 16 to 31

### CODE REVIEW

**Comment by make-all** [comment]
@cykus, as you originally submitted this device, do you have any comments on this change?

**Comment by piotrek2555** [comment]
I only copy and paste from other device. In my app smart I have only to 31 degrees celsius, but I not sure or device support Fahrenheit temperature.

**Comment by make-all** [comment]
Thank you for confirming

**Comment by cykus** [comment]
i set it to 88 because of debug info on iot tuya, as @piotrek2555 said in app i can set it only to 31c
`temp_set | Integer | {   "unit": "℃",   "min": 160,   "max": 880,   "scale": 1,   "step": 5 }`

on debug info i see second dps for Fahrenheit, but i don't know have tu use two set_temps
`temp_set_f | Integer | {   "unit": "℉",   "min": 61,   "max": 88,   "scale": 0,   "step": 1 }`

**Pull request merged**
