### PR TITLE
Update stl_siren.yaml

### PR DESCRIPTION
**Pull request by VladimirTuzovGitHub**
The final integration is fully tested. Please update this code. Thank you very much for your support!

### CODE REVIEW

**Comment by make-all** [comment]
I don't see this as an improvement, sorry.

**Comment by VladimirTuzovGitHub** [comment]
Hello! The improvements are that your code does not have the setting for selecting the siren sound and setting the siren sound time. We discussed this in the topic [https://github.com/make-all/tuya-local/issues/2350](url). I assume that these settings are important in the integration so that any user can configure them from the HA interface and does not need to do it through the Tuya application, which is very inconvenient.

**Comment by make-all** [comment]
The settings are there in the siren entity.

**Comment by VladimirTuzovGitHub** [comment]
I am talking about basic settings that will be available to the average user in a human-readable interface, and not through event or parameter calls in automations. In your configuration, in the very essence of the serena, there are only attributes of melodies and time in the form of a list.

**Pull request closed without merging**
