### PR TITLE
Fix detection alecoair d12 home

### PR DESCRIPTION
**Pull request by romicaiarca**
Fixing https://github.com/make-all/tuya-local/issues/397

### CODE REVIEW

**Comment by make-all** [comment]
Please try the latest main HEAD before making further reversions.

**Comment by romicaiarca** [comment]
> Please try the latest main HEAD before making further reversions.

Ok, Now should be fine. I've tested with this version and works fine :)

**Comment by make-all** [comment]
1. The advantage of using the standard HA fan entity is that it will just work with voice assistants and other external integrations.  The fan uses a slider, I don't think it is a major issue, as it should snap to the closest setting: right for high, middle for low, left for off.
2. This seems to be an issue, but I cannot see any difference between the humidity in your config and in the installed one.  Are there any messages in the log?  It may be that recent changes to scale handling have messed up some cases where scale is not specified and should default to 1.  Or the device may not be returning any value for some values, or some dehumidifiers return "CO" when in constant humidifying mode, which could be causing this.

**Comment by romicaiarca** [comment]
> 



> 1. The advantage of using the standard HA fan entity is that it will just work with voice assistants and other external integrations that tend to use the fan.increase_speed and fan.decrease_speed commands rather than setting a specific value.  The fan uses a slider, I don't think it is a major issue, as it should snap to the closest setting: right for high, middle for low, left for off.    You can manually configure your UI to use "High" and "Low" buttons that call fan.set_percentage (percentage=50 and percentage=100 respectively) if you don't like the default UI.
> 2. This seems to be an issue, but I cannot see any difference between the humidity in your config and in the installed one.  Are there any messages in the log?  It may be that recent changes to scale handling have messed up some cases where scale is not specified and should default to 1.  Or the device may not be returning any value for some modes, or some dehumidifiers return "CO" when in constant humidifying mode, which could be causing this.

1. Ok, then there is other issue. It looks like when I slide to left to 0, the dehumidifier is not turning off. 
2. After multiple restarts of HA, now the slider/display of value are ok.

**Comment by make-all** [comment]
Its a while since I had a fan that works with HA (now I only have an air conditioning unit, but that works differently, not with a separate fan entity). I thought I remembered them working like that, but maybe they have changed, or I am misremembering.

**Comment by romicaiarca** [comment]
@make-all , should I close the pull request since you are saying that is better to keep the current configuration for this new device?

**Comment by make-all** [comment]
If the device is working in the current release, then please close this pull request.

If there is a problem that needs addressing still, maybe make a new branch based off the current HEAD, because this is saying it cannot be rebased due to conflicts.

**Pull request closed without merging**
