### PR TITLE
Add support for Antela smart plug (Italian socket)

### PR DESCRIPTION
**Pull request by pmazz**
Additional device info here: https://www.amazon.it/dp/B09NBN31HW

### CODE REVIEW

**Comment by make-all** [comment]
What is the difference between this and existing configs?  Specifically "smartplugv2_energy", which seems to match all of the dps.

I don't want to end up with thousands of configs that differ just by their name.

**Comment by pmazz** [comment]
Yes, "smartplugv2_energy" is the most similar config which I found, except for the 46 dp (overcharge cutoff) which I don't seem to have.
I understand you don't want to have many similar configs, so let me know how to proceed.
Thanks.

**Comment by make-all** [comment]
I think you can just ignore the overcharge_cutoff switch, as it is already marked as optional.

**Comment by pmazz** [comment]
Great, thank you.
👍

**Pull request closed without merging**
