### PR TITLE
Update qlima_d820a_dehumidifier.yaml

### PR DESCRIPTION
**Pull request by Blcktape**
Add current humidity sensor and change a description.

### CODE REVIEW

**Comment by make-all** [comment]
Current humidity is already part of the humidifier entity.
Changing the naming is just a personal preference, and can be disruptive if other users have automations set up using the current name.

**Comment by Blcktape** [comment]
Current humidity is indeed already part of the humidifier entity. But you are not able to use it as its own sensor entity just like temperature.
To be able to do something with the data like displaying it in a graph the current humidity should be available and in my oppinion disclosed as an sensor.

**Comment by make-all** [comment]
You can display a graph of the current_humidity attribute of the humidifier entity.

**Comment by Blcktape** [comment]
> You can display a graph of the current_humidity attribute of the humidifier entity.

I had an issue with that using an "Statistics graph card". It would only show "sensor" entities. As "current_humidity" isnt disclosed as an sensor it would not be able to display it as such in my case.
If there is a different way i would gladly like to know.

**Comment by make-all** [comment]
Template sensors can get around limitations like this. Or you can use the standard History graph car, which supports most entity types.

**Comment by Blcktape** [comment]
> Template sensors can get around limitations like this. Or you can use the standard History graph car, which supports most entity types.

Thank you, this fixed my problem as i did not now "template sensors" existed. This patch can be discarded.

**Pull request closed without merging**
