### PR TITLE
Add support for Shinco 50D Dehumidifier

### PR DESCRIPTION
**Pull request by shiner66**

### CODE REVIEW

**Comment by make-all** [comment]
This is substantially the same as Shinco 30D. Only the ionizer switch seems to be missing.

**Comment by shiner66** [comment]
It is, but it is necessary to make the integration recognize it.

**Comment by make-all** [comment]
You seem to have deleted your branch. Does that mean the commit I made above is working?

**Comment by shiner66** [comment]
It’s unstable, I tried multiple times to add the dehumidifier and it doesn’t always recognize it, but most of the times it does work.

Sent with Spark
Il 14 mar 2024, 06:06 +0100, Jason Rumney ***@***.***>, ha scritto:

**Pull request closed without merging**
